### ISSUE TITLE
Optional params not working.

### ISSUE THREAD

**Issue by saggiyogesh** [possibilities/micro-api#20]
Seems like `uniloc` doesn't support optional params.
Configuring this route`/test/:name/:id/:fields?`, giving this error

```
Error: Unirouter Assertion Failed: Path `/test/:name/:id/:fields?` does not contain the `#` or `?` characters
```

Please suggest any alternative.

**Comment by possibilities** [comment]
Totally open to incorporating a matcher that can do more. I've run into similar limitations. Any  libraries that you have in mind that we should consider?

**Comment by saggiyogesh** [comment]
- https://www.npmjs.com/package/url-pattern
- https://www.npmjs.com/package/route-parser
- https://www.npmjs.com/package/route-pattern

`url-pattern`  is lightest of all, I think and used by a micro module `https://github.com/dotcypress/micro-route`

**Comment by saggiyogesh** [comment]
Is any library helpful?
Your thoughts, please.

**Comment by possibilities** [comment]
Hey, sorry I managed to miss that you had replied! :( I'll make some time this weekend to consider the available libraries and integrate one.

**Comment by possibilities** [comment]
Check it out, we now use: https://github.com/pillarjs/path-match
You can see your case covered here in the underlying library: https://github.com/pillarjs/path-to-regexp/blob/master/test.ts#L499
